cmake_minimum_required(VERSION 3.23)

set(SANITIZER_SUPPORTED OFF)
option(ENABLE_SANITIZER "Enable Address Sanitizer" OFF)

if (MINGW)
  if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(SANITIZER_SUPPORTED OFF)
  elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(SANITIZER_SUPPORTED ON)
  endif()
elseif (MSVC OR CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
  set(SANITIZER_SUPPORTED ON)
endif()

if (SANITIZER_SUPPORTED)
  if (ENABLE_SANITIZER)
    message(STATUS "Enabling AddressSanitizer")
    if(MSVC AND CMAKE_BUILD_TYPE STREQUAL "Debug")
      add_compile_options(/fsanitize=address /Zi)
      add_link_options(/INCREMENTAL:NO)
    else()
      add_compile_options(-fsanitize=address -fno-omit-frame-pointer -g)
      add_link_options(-fsanitize=address)
    endif()
  endif()
else()
  if (ENABLE_SANITIZER)
    message(WARNING "Sanitizers are NOT supported with ${CMAKE_CXX_COMPILER_ID} on MinGW. Skipping.")
  endif()
endif()
